config/routes.rb
Rails.application.routes.draw do
  resources :mail_templates
  resources :posts
  resource :previewer, only: :create
  root to: 'welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/mail_template.rb
class MailTemplate < ApplicationRecord
  has_rich_text :content
end

app/models/post.rb
class Post < ApplicationRecord
  has_rich_text :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mail_templates_controller.rb
class MailTemplatesController < ApplicationController
  before_action :set_mail_template, only: %i[ show edit update destroy ]

  # GET /mail_templates
  def index
    @mail_templates = MailTemplate.all
  end

  # GET /mail_templates/1
  def show
  end

  # GET /mail_templates/new
  def new
    @mail_template = MailTemplate.new
  end

  # GET /mail_templates/1/edit
  def edit
  end

  # POST /mail_templates
  def create
    @mail_template = MailTemplate.new(mail_template_params)

    if @mail_template.save
      redirect_to @mail_template, notice: "Mail template was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /mail_templates/1
  def update
    if @mail_template.update(mail_template_params)
      redirect_to @mail_template, notice: "Mail template was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /mail_templates/1
  def destroy
    @mail_template.destroy
    redirect_to mail_templates_url, notice: "Mail template was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mail_template
      @mail_template = MailTemplate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mail_template_params
      params.require(:mail_template).permit(:name, :subject, :content)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: "Post was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: "Post was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: "Post was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/previewers_controller.rb
# previewers_controller.rb
class PreviewersController < ApplicationController
  def create
    template = Liquid::Template.parse(params[:content])

    # {{ example }} => "Hello World"
    text = template.render(fields)
    render plain: text
  rescue Liquid::SyntaxError
    render plain: params[:content]
  end

  private

  def fields
    {}.tap do |hash|
      # hash["post_title"] = Post.all.sample.title if params[:content].include?("post_title")
      hash["post_title"] = "This is a post title"
      hash["example_number"] = "1234"
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light py-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="#" data-config-id="brand">
      <%= image_tag 'logo.png', class: 'img-fluid' %>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nav">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="nav">
      <ul class="d-none d-lg-flex navbar-nav mt-3 mt-lg-0 mb-3 mb-lg-0">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <ul class="navbar-nav mt-3 mt-lg-0 mb-3 mb-lg-0 d-lg-none">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li class="nav-item me-4">
  <%= link_to "Home", root_path, class: 'nav-link' %>
</li>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LiquidTemplates358</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class='bg-light'>
    <div class="container bg-white border pb-3">
      <%= render 'layouts/navigation' %>
      <% flash.each do |type, msg| %>
        <% if type == 'alert' %>
          <%= content_tag :div, msg, class: "alert alert-danger", role: :alert %>
          <% else %>
          <%= content_tag :div, msg, class: "alert alert-primary", role: :alert %>
        <% end %>
      <% end %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/mail_templates/_form.html.erb
<%= form_with(model: mail_template) do |form| %>
  <% if mail_template.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mail_template.errors.count, "error") %> prohibited this mail_template from being saved:</h2>

      <ul>
        <% mail_template.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :subject, class: 'form-label' %>
    <%= form.text_field :subject, class: 'form-control' %>
  </div>

  <%= content_tag :div, class: 'mb-3',
    "data-controller": "previewer",
    "data-previewer-url-value": previewer_path do %>

    <%= form.label :content, class: 'form-label' %>
    <%= form.rich_text_area :content, class: 'form-control mb-3', "data-previewer-target": "input" %>

    <div class="card mb-3">
      <div class="card-body">
        <div data-previewer-target="output"></div>
      </div>
    </div>

    <div class="card mb-3">
      <div class="card-body">
        <div>Available Variables</div>
        <div>Posts</div>
        <ul>
          <li>Title - {{ post_title }}</li>
        </ul>
        <div>Extras</div>
        <ul>
          <li>Random Number - {{ example_number }}</li>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/mail_templates/_mail_template.html.erb
<div id="<%= dom_id mail_template %>" class="scaffold_record">
  <p>
    <strong>Name:</strong>
    <%= mail_template.name %>
  </p>

  <p>
    <strong>Subject:</strong>
    <%= mail_template.subject %>
  </p>

</div>

app/views/mail_templates/edit.html.erb
<h1>Editing mail template</h1>

<%= render "form", mail_template: @mail_template %>

<br>

<div>
  <%= link_to "Show this mail template", @mail_template %> |
  <%= link_to "Back to mail templates", mail_templates_path %>
</div>

app/views/mail_templates/index.html.erb
<h1>Mail template</h1>

<table class='table'>
  <thead>
    <th>Name</th>
    <th>Subject</th>
    
    <th colspan=3>Actions</th>
  </thead>
  <tbody>
    <% @mail_templates.each do |mail_template| %>
      <tr>
        <td><%= mail_template.name %></td>
        <td><%= mail_template.subject %></td>
      
        <td><%= link_to "Show", mail_template_path(mail_template) %></td>
        <td><%= link_to "Edit", edit_mail_template_path(mail_template) %></td>
        <td>
          <%= link_to "Delete", mail_template_path(mail_template),
            "data-turbo-method": :delete,
            "data-turbo-confirm": "Are you sure?" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New mail template", new_mail_template_path %>

app/views/mail_templates/new.html.erb
<h1>New mail template</h1>

<%= render "form", mail_template: @mail_template %>

<br>

<div>
  <%= link_to "Back to mail templates", mail_templates_path %>
</div>

app/views/mail_templates/show.html.erb
<%= render @mail_template %>

<div>
  <%= link_to "Edit", edit_mail_template_path(@mail_template) %> |
  <%= link_to "Destroy", mail_template_path(@mail_template),
    "data-turbo-method": :delete,
    "data-turbo-confirm": "Are you sure?" %> |
  <%= link_to "Back to mail templates", mail_templates_path %>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mb-3">
    <%= form.label :content, class: 'form-label' %>
    <%= form.rich_text_area :content, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="scaffold_record">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<h1>Post</h1>

<table class='table'>
  <thead>
    <th>Title</th>
    
    <th colspan=3>Actions</th>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
      
        <td><%= link_to "Show", post_path(post) %></td>
        <td><%= link_to "Edit", edit_post_path(post) %></td>
        <td>
          <%= link_to "Delete", post_path(post),
            "data-turbo-method": :delete,
            "data-turbo-confirm": "Are you sure?" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<%= render @post %>

<div>
  <%= link_to "Edit", edit_post_path(@post) %> |
  <%= link_to "Destroy", post_path(@post),
    "data-turbo-method": :delete,
    "data-turbo-confirm": "Are you sure?" %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>